#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,tmux,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$PWD
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

